const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
const load=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
const save=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
let ingredients=load('usahaku.ingredients'), products=load('usahaku.products'), sales=load('usahaku.sales'), cart=[];
let lastHpp={name:'Produk baru',hpp:4700,price:7834,profit:3134,margin:40,total:235000};
const titles={dashboard:'Ringkasan Usaha',hpp:'Kalkulator HPP',modal:'Analisis Balik Modal',bahan:'Database Bahan Baku',produk:'Produk & Resep',kasir:'Kasir'};
function go(page){$$('.page').forEach(x=>x.classList.toggle('active',x.id===page));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#pageTitle').textContent=titles[page];$('.sidebar').classList.remove('open');scrollTo({top:0,behavior:'smooth'});if(page==='dashboard')renderDashboard();if(page==='kasir')renderCashier()}
$$('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('.go').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');
$('#today').textContent=new Intl.DateTimeFormat('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date()).toUpperCase();
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function calcHpp(){const total=['materialCost','packagingCost','laborCost','otherCost'].reduce((a,id)=>a+(Number($('#'+id).value)||0),0);const qty=Math.max(1,Number($('#productionQty').value)||1),margin=Math.min(95,Math.max(0,Number($('#marginTarget').value)||0));const hpp=total/qty,price=hpp/(1-margin/100),profit=price-hpp;lastHpp={name:$('#hppName').value.trim()||'Produk baru',hpp,price,profit,margin,total};$('#hppUnit').textContent=money(hpp);$('#hppTotal').textContent=money(total);$('#idealPrice').textContent=money(price);$('#unitProfit').textContent=money(profit);$('#resultMargin').textContent=margin.toLocaleString('id-ID')+'%'}
$('#hppForm').onsubmit=e=>{e.preventDefault();calcHpp();toast('Perhitungan HPP selesai')};['materialCost','packagingCost','laborCost','otherCost','productionQty','marginTarget'].forEach(id=>$('#'+id).oninput=calcHpp);calcHpp();
$('#saveProduct').onclick=()=>{calcHpp();const existing=products.findIndex(p=>p.name.toLowerCase()===lastHpp.name.toLowerCase());const item={...lastHpp,id:existing>=0?products[existing].id:Date.now(),createdAt:new Date().toISOString()};if(existing>=0)products[existing]=item;else products.unshift(item);save('usahaku.products',products);renderProducts();toast('Produk berhasil disimpan')};
function calcRoi(){const capital=+$('#initialCapital').value||0,revenue=+$('#monthlyRevenue').value||0,cost=(+$('#variableCost').value||0)+(+$('#operationalCost').value||0),profit=revenue-cost,bep=profit>0?capital/profit:Infinity,roi=capital>0?(profit*12/capital)*100:0,margin=revenue>0?(profit/revenue)*100:0;$('#bepMonths').textContent=isFinite(bep)?bep.toLocaleString('id-ID',{maximumFractionDigits:1})+' bulan':'Tidak tercapai';$('#monthlyProfit').textContent=money(profit);$('#annualRoi').textContent=roi.toLocaleString('id-ID',{maximumFractionDigits:1})+'%';$('#netMargin').textContent=margin.toLocaleString('id-ID',{maximumFractionDigits:1})+'%';const ok=profit>0;$('#feasibility').className='health '+(ok?'good':'bad');$('#feasibility').textContent=ok?'● Skenario usaha layak':'● Biaya lebih besar dari omzet'}
$('#roiForm').onsubmit=e=>{e.preventDefault();calcRoi();toast('Analisis bisnis diperbarui')};['initialCapital','monthlyRevenue','variableCost','operationalCost'].forEach(id=>$('#'+id).oninput=calcRoi);calcRoi();
$('#addIngredient').onclick=()=>$('#ingredientDialog').showModal();$('#ingredientForm').onsubmit=e=>{e.preventDefault();ingredients.unshift({id:Date.now(),name:$('#ingredientName').value.trim(),price:+$('#ingredientPrice').value,amount:+$('#ingredientAmount').value,unit:$('#ingredientUnit').value});save('usahaku.ingredients',ingredients);e.target.reset();$('#ingredientDialog').close();renderIngredients();toast('Bahan berhasil ditambahkan')};
function renderIngredients(){const tbody=$('#ingredientTable');tbody.innerHTML=ingredients.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${money(x.price)}</td><td>${num(x.amount)} ${esc(x.unit)}</td><td><b>${money(x.price/x.amount)} / ${esc(x.unit)}</b></td><td><button class="delete" data-del-ing="${x.id}">Hapus</button></td></tr>`).join('');$('#ingredientEmpty').style.display=ingredients.length?'none':'block';$$('[data-del-ing]').forEach(b=>b.onclick=()=>{ingredients=ingredients.filter(x=>x.id!=b.dataset.delIng);save('usahaku.ingredients',ingredients);renderIngredients()})}
function renderProducts(){const grid=$('#productGrid');grid.innerHTML=products.map(p=>`<article class="product-card"><div class="product-top"><h3>${esc(p.name)}</h3><button class="delete" data-del-product="${p.id}">×</button></div><p>Target margin ${num(p.margin)}%</p><div class="product-metrics"><span><small>HPP</small><b>${money(p.hpp)}</b></span><span><small>Harga jual</small><b>${money(p.price)}</b></span></div></article>`).join('');$('#productEmpty').style.display=products.length?'none':'block';$$('[data-del-product]').forEach(b=>b.onclick=()=>{products=products.filter(x=>x.id!=b.dataset.delProduct);save('usahaku.products',products);renderProducts();renderCashier()})}
function renderCashier(){const wrap=$('#cashierProducts');wrap.innerHTML=products.length?products.map(p=>`<button class="cashier-product" data-add-cart="${p.id}"><b>${esc(p.name)}</b><small>${money(p.price)}</small></button>`).join(''):'<div class="empty">Simpan produk dari Kalkulator HPP terlebih dahulu.</div>';$$('[data-add-cart]').forEach(b=>b.onclick=()=>{const p=products.find(x=>x.id==b.dataset.addCart),line=cart.find(x=>x.id===p.id);line?line.qty++:cart.push({...p,qty:1});renderCart()});renderCart();renderSales()}
function renderCart(){const el=$('#cartItems');el.classList.toggle('empty',!cart.length);el.innerHTML=cart.length?cart.map(x=>`<div class="cart-line"><span><b>${esc(x.name)}</b><br><small>${x.qty} × ${money(x.price)}</small></span><button data-cart-remove="${x.id}">−</button></div>`).join(''):'Keranjang masih kosong.';$('#cartTotal').textContent=money(cart.reduce((a,x)=>a+x.price*x.qty,0));$$('[data-cart-remove]').forEach(b=>b.onclick=()=>{const x=cart.find(i=>i.id==b.dataset.cartRemove);x.qty--;if(x.qty<=0)cart=cart.filter(i=>i.id!==x.id);renderCart()})}
$('#checkout').onclick=()=>{if(!cart.length)return toast('Pilih produk terlebih dahulu');const total=cart.reduce((a,x)=>a+x.price*x.qty,0),profit=cart.reduce((a,x)=>a+x.profit*x.qty,0);sales.unshift({id:Date.now(),date:new Date().toISOString(),items:cart.map(x=>({name:x.name,qty:x.qty})),total,profit});save('usahaku.sales',sales);cart=[];renderCashier();renderDashboard();toast('Transaksi berhasil dicatat')};
$('#clearSales').onclick=()=>{if(sales.length&&confirm('Hapus seluruh riwayat transaksi?')){sales=[];save('usahaku.sales',sales);renderCashier();renderDashboard()}};
function renderSales(){const body=$('#salesTable');body.innerHTML=sales.map(s=>`<tr><td>${new Date(s.date).toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short'})}</td><td>${s.items.map(i=>esc(i.name)+' ×'+i.qty).join(', ')}</td><td><b>${money(s.total)}</b></td><td>${money(s.profit)}</td></tr>`).join('');$('#salesEmpty').style.display=sales.length?'none':'block'}
function renderDashboard(){const revenue=sales.reduce((a,x)=>a+x.total,0),profit=sales.reduce((a,x)=>a+x.profit,0);$('#statRevenue').textContent=money(revenue);$('#statProfit').textContent=money(profit);$('#heroProfit').textContent=money(profit);$('#statProducts').textContent=products.length;$('#statIngredients').textContent=ingredients.length;const recent=$('#recentSales');recent.classList.toggle('empty',!sales.length);recent.innerHTML=sales.length?sales.slice(0,4).map(s=>`<div class="recent-row"><span><b>${s.items.map(i=>esc(i.name)).join(', ')}</b><br><small>${new Date(s.date).toLocaleDateString('id-ID',{day:'numeric',month:'short'})}</small></span><b>${money(s.total)}</b></div>`).join(''):'Belum ada transaksi. Mulai dari menu Kasir.'}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function num(v){return Number(v).toLocaleString('id-ID',{maximumFractionDigits:2})}
renderIngredients();renderProducts();renderCashier();renderDashboard();
