const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
const load=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
const save=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
let ingredients=load('usahaku.ingredients'), products=load('usahaku.products'), sales=load('usahaku.sales'), cart=[];
let lastHpp={name:'Produk baru',hpp:4700,price:7834,profit:3134,margin:40,total:235000};
const titles={dashboard:'Ringkasan Usaha',panduan:'Panduan Memulai Usaha',hpp:'Kalkulator HPP',modal:'Analisis Balik Modal',bahan:'Database Bahan Baku',produk:'Produk & Resep',kasir:'Kasir'};
function go(page){$$('.page').forEach(x=>x.classList.toggle('active',x.id===page));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#pageTitle').textContent=titles[page];$('.sidebar').classList.remove('open');scrollTo({top:0,behavior:'smooth'});if(page==='dashboard')renderDashboard();if(page==='kasir')renderCashier()}
$$('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('.go').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');
$('#today').textContent=new Intl.DateTimeFormat('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date()).toUpperCase();
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function calcHpp(){const total=['materialCost','packagingCost','laborCost','otherCost'].reduce((a,id)=>a+(Number($('#'+id).value)||0),0);const qty=Math.max(1,Number($('#productionQty').value)||1),margin=Math.min(95,Math.max(0,Number($('#marginTarget').value)||0));const hpp=total/qty,price=hpp/(1-margin/100),profit=price-hpp;lastHpp={name:$('#hppName').value.trim()||'Produk baru',hpp,price,profit,margin,total};$('#hppUnit').textContent=money(hpp);$('#hppTotal').textContent=money(total);$('#idealPrice').textContent=money(price);$('#unitProfit').textContent=money(profit);$('#resultMargin').textContent=margin.toLocaleString('id-ID')+'%'}
$('#hppForm').onsubmit=e=>{e.preventDefault();calcHpp();toast('Perhitungan HPP selesai')};['materialCost','packagingCost','laborCost','otherCost','productionQty','marginTarget'].forEach(id=>$('#'+id).oninput=calcHpp);calcHpp();
$('#saveProduct').onclick=()=>{calcHpp();const existing=products.findIndex(p=>p.name.toLowerCase()===lastHpp.name.toLowerCase());const item={...lastHpp,id:existing>=0?products[existing].id:Date.now(),createdAt:new Date().toISOString()};if(existing>=0)products[existing]=item;else products.unshift(item);save('usahaku.products',products);renderProducts();toast('Produk berhasil disimpan')};
function calcRoi(){const capital=+$('#initialCapital').value||0,revenue=+$('#monthlyRevenue').value||0,cost=(+$('#variableCost').value||0)+(+$('#operationalCost').value||0),profit=revenue-cost,bep=profit>0?capital/profit:Infinity,roi=capital>0?(profit*12/capital)*100:0,margin=revenue>0?(profit/revenue)*100:0;$('#bepMonths').textContent=isFinite(bep)?bep.toLocaleString('id-ID',{maximumFractionDigits:1})+' bulan':'Tidak tercapai';$('#monthlyProfit').textContent=money(profit);$('#annualRoi').textContent=roi.toLocaleString('id-ID',{maximumFractionDigits:1})+'%';$('#netMargin').textContent=margin.toLocaleString('id-ID',{maximumFractionDigits:1})+'%';const ok=profit>0;$('#feasibility').className='health '+(ok?'good':'bad');$('#feasibility').textContent=ok?'● Skenario usaha berpotensi untung':'● Biaya lebih besar dari omzet'}
$('#roiForm').onsubmit=e=>{e.preventDefault();calcRoi();toast('Analisis bisnis diperbarui')};['initialCapital','monthlyRevenue','variableCost','operationalCost'].forEach(id=>$('#'+id).oninput=calcRoi);calcRoi();
$('#addIngredient').onclick=()=>$('#ingredientDialog').showModal();$('#ingredientForm').onsubmit=e=>{e.preventDefault();ingredients.unshift({id:Date.now(),name:$('#ingredientName').value.trim(),price:+$('#ingredientPrice').value,amount:+$('#ingredientAmount').value,unit:$('#ingredientUnit').value});save('usahaku.ingredients',ingredients);e.target.reset();$('#ingredientDialog').close();renderIngredients();toast('Bahan berhasil ditambahkan')};
function renderIngredients(){const tbody=$('#ingredientTable');tbody.innerHTML=ingredients.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${money(x.price)}</td><td>${num(x.amount)} ${esc(x.unit)}</td><td><b>${money(x.price/x.amount)} / ${esc(x.unit)}</b></td><td><button class="delete" data-del-ing="${x.id}">Hapus</button></td></tr>`).join('');$('#ingredientEmpty').style.display=ingredients.length?'none':'block';$$('[data-del-ing]').forEach(b=>b.onclick=()=>{ingredients=ingredients.filter(x=>x.id!=b.dataset.delIng);save('usahaku.ingredients',ingredients);renderIngredients()})}
function renderProducts(){const grid=$('#productGrid');grid.innerHTML=products.map(p=>`<article class="product-card"><div class="product-top"><h3>${esc(p.name)}</h3><button class="delete" data-del-product="${p.id}">×</button></div><p>Target margin ${num(p.margin)}%</p><div class="product-metrics"><span><small>HPP</small><b>${money(p.hpp)}</b></span><span><small>Harga jual</small><b>${money(p.price)}</b></span></div></article>`).join('');$('#productEmpty').style.display=products.length?'none':'block';$$('[data-del-product]').forEach(b=>b.onclick=()=>{products=products.filter(x=>x.id!=b.dataset.delProduct);save('usahaku.products',products);renderProducts();renderCashier()})}
function renderCashier(){const wrap=$('#cashierProducts');wrap.innerHTML=products.length?products.map(p=>`<button class="cashier-product" data-add-cart="${p.id}"><b>${esc(p.name)}</b><small>${money(p.price)}</small></button>`).join(''):'<div class="empty">Simpan produk dari Kalkulator HPP terlebih dahulu.</div>';$$('[data-add-cart]').forEach(b=>b.onclick=()=>{const p=products.find(x=>x.id==b.dataset.addCart),line=cart.find(x=>x.id===p.id);line?line.qty++:cart.push({...p,qty:1});renderCart()});renderCart();renderSales()}
function renderCart(){const el=$('#cartItems');el.classList.toggle('empty',!cart.length);el.innerHTML=cart.length?cart.map(x=>`<div class="cart-line"><span><b>${esc(x.name)}</b><br><small>${x.qty} × ${money(x.price)}</small></span><button data-cart-remove="${x.id}">−</button></div>`).join(''):'Keranjang masih kosong.';$('#cartTotal').textContent=money(cart.reduce((a,x)=>a+x.price*x.qty,0));$$('[data-cart-remove]').forEach(b=>b.onclick=()=>{const x=cart.find(i=>i.id==b.dataset.cartRemove);x.qty--;if(x.qty<=0)cart=cart.filter(i=>i.id!==x.id);renderCart()})}
$('#checkout').onclick=()=>{if(!cart.length)return toast('Pilih produk terlebih dahulu');const total=cart.reduce((a,x)=>a+x.price*x.qty,0),profit=cart.reduce((a,x)=>a+x.profit*x.qty,0);sales.unshift({id:Date.now(),date:new Date().toISOString(),items:cart.map(x=>({name:x.name,qty:x.qty})),total,profit});save('usahaku.sales',sales);cart=[];renderCashier();renderDashboard();toast('Transaksi berhasil dicatat')};
$('#clearSales').onclick=()=>{if(sales.length&&confirm('Hapus seluruh riwayat transaksi?')){sales=[];save('usahaku.sales',sales);renderCashier();renderDashboard()}};
function renderSales(){const body=$('#salesTable');body.innerHTML=sales.map(s=>`<tr><td>${new Date(s.date).toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short'})}</td><td>${s.items.map(i=>esc(i.name)+' ×'+i.qty).join(', ')}</td><td><b>${money(s.total)}</b></td><td>${money(s.profit)}</td></tr>`).join('');$('#salesEmpty').style.display=sales.length?'none':'block'}
function renderDashboard(){const revenue=sales.reduce((a,x)=>a+x.total,0),profit=sales.reduce((a,x)=>a+x.profit,0);$('#statRevenue').textContent=money(revenue);$('#statProfit').textContent=money(profit);$('#heroProfit').textContent=money(profit);$('#statProducts').textContent=products.length;$('#statIngredients').textContent=ingredients.length;const recent=$('#recentSales');recent.classList.toggle('empty',!sales.length);recent.innerHTML=sales.length?sales.slice(0,4).map(s=>`<div class="recent-row"><span><b>${s.items.map(i=>esc(i.name)).join(', ')}</b><br><small>${new Date(s.date).toLocaleDateString('id-ID',{day:'numeric',month:'short'})}</small></span><b>${money(s.total)}</b></div>`).join(''):'Belum ada transaksi. Mulai dari menu Kasir.'}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function num(v){return Number(v).toLocaleString('id-ID',{maximumFractionDigits:2})}

function installBeginnerGuide(){
  const css=document.createElement('link');css.rel='stylesheet';css.href='guide.css';document.head.appendChild(css);
  const nav=$('#nav'), hppNav=nav.querySelector('[data-page="hpp"]');
  const guideNav=document.createElement('button');guideNav.className='nav-item';guideNav.dataset.page='panduan';guideNav.innerHTML='<span>?</span>Panduan Pemula';nav.insertBefore(guideNav,hppNav);guideNav.onclick=()=>go('panduan');
  const dashboard=$('#dashboard'), hero=dashboard.querySelector('.hero');
  hero.insertAdjacentHTML('afterend',`<div class="beginner-banner"><div><h3>Baru mulai usaha dan bingung istilahnya?</h3><p>Pelajari alur paling sederhana, arti HPP, omzet, profit, margin, ROI, dan BEP sebelum menghitung.</p></div><button class="btn btn-primary" id="openGuide">Buka panduan pemula →</button></div>`);
  $('#openGuide').onclick=()=>go('panduan');
  const guide=document.createElement('section');guide.className='page';guide.id='panduan';guide.innerHTML=`
    <div class="section-intro"><div><p class="eyebrow">MULAI DARI NOL</p><h2>Belajar angka usaha tanpa bahasa rumit.</h2><p>Tidak harus jago akuntansi. Ikuti urutan ini agar keputusan harga dan modalmu tidak hanya berdasarkan perkiraan.</p></div></div>
    <div class="guide-steps">
      <article class="guide-step"><span class="step-no">1</span><h3>Catat semua biaya</h3><p>Masukkan bahan, kemasan, tenaga kerja, listrik, dan biaya kecil lain. Biaya yang terlupa membuat keuntungan terlihat lebih besar dari kenyataan.</p></article>
      <article class="guide-step"><span class="step-no">2</span><h3>Hitung HPP</h3><p>HPP menunjukkan biaya untuk menghasilkan satu produk. Ini adalah batas dasar sebelum menentukan harga jual.</p></article>
      <article class="guide-step"><span class="step-no">3</span><h3>Tentukan harga</h3><p>Tambahkan ruang keuntungan, potongan harga, risiko bahan rusak, dan biaya tak terduga. Jangan sekadar mengikuti harga pesaing.</p></article>
      <article class="guide-step"><span class="step-no">4</span><h3>Uji balik modal</h3><p>Bandingkan modal awal dengan keuntungan bersih bulanan untuk memperkirakan kapan modal kembali.</p></article>
    </div>
    <div class="guide-grid">
      <article class="panel"><p class="eyebrow">KAMUS USAHA</p><h3>Istilah penting dalam bahasa sederhana</h3><div class="glossary">
        <details class="term" open><summary>HPP — Harga Pokok Produksi</summary><p>Seluruh biaya untuk membuat <strong>satu produk</strong>. Rumus sederhananya: total biaya produksi ÷ jumlah produk jadi. Contoh: biaya Rp200.000 menghasilkan 40 gelas, maka HPP-nya Rp5.000 per gelas.</p></details>
        <details class="term"><summary>Omzet</summary><p>Total uang dari penjualan <strong>sebelum dikurangi biaya</strong>. Menjual 100 produk seharga Rp10.000 menghasilkan omzet Rp1.000.000—tetapi itu belum tentu keuntungan.</p></details>
        <details class="term"><summary>Profit atau keuntungan</summary><p>Uang yang tersisa setelah pendapatan dikurangi biaya. <strong>Profit kotor</strong> baru mengurangi HPP; <strong>profit bersih</strong> juga sudah mengurangi sewa, gaji, listrik, promosi, dan biaya operasional lain.</p></details>
        <details class="term"><summary>Margin</summary><p>Persentase keuntungan dibandingkan harga jual. Jika harga jual Rp10.000 dan profit Rp4.000, marginnya 40%. Margin berbeda dari markup, yang membandingkan keuntungan dengan biaya.</p></details>
        <details class="term"><summary>Biaya tetap dan biaya variabel</summary><p><strong>Biaya tetap</strong> relatif sama walau penjualan berubah, misalnya sewa. <strong>Biaya variabel</strong> naik saat produksi bertambah, misalnya bahan dan kemasan.</p></details>
        <details class="term"><summary>BEP — Break-Even Point / Balik Modal</summary><p>Perkiraan titik ketika keuntungan yang terkumpul sudah menutup modal awal. Jika modal Rp12 juta dan profit bersih Rp2 juta per bulan, estimasi BEP adalah 6 bulan.</p></details>
        <details class="term"><summary>ROI — Return on Investment</summary><p>Persentase hasil dibandingkan modal. ROI membantu membandingkan apakah hasil usaha sepadan dengan uang yang ditanam, tetapi bukan jaminan keuntungan masa depan.</p></details>
      </div></article>
      <aside><article class="panel"><p class="eyebrow">SEBELUM MENGHITUNG</p><h3>Siapkan angka berikut</h3><div class="checklist">
        <div class="check-item"><span>✓</span><div><b>Harga dan jumlah bahan</b><br>Gunakan harga pembelian terbaru.</div></div>
        <div class="check-item"><span>✓</span><div><b>Hasil produksi nyata</b><br>Catat berapa produk layak jual, bukan perkiraan ideal.</div></div>
        <div class="check-item"><span>✓</span><div><b>Biaya kemasan dan tenaga</b><br>Waktu kerjamu juga memiliki nilai.</div></div>
        <div class="check-item"><span>✓</span><div><b>Pengeluaran bulanan</b><br>Sewa, listrik, internet, gaji, dan promosi.</div></div>
      </div></article>
      <article class="example-box"><p class="eyebrow">CONTOH CEPAT</p><h3>Es kopi susu — 50 gelas</h3><p>Bahan Rp150.000 + kemasan Rp25.000 + tenaga Rp50.000 + biaya lain Rp10.000.</p><div class="example-math"><div><span>Total biaya</span><b>Rp235.000</b></div><div><span>HPP per gelas</span><b>Rp4.700</b></div><div><span>Harga margin 40%</span><b>± Rp7.834</b></div></div></article></aside>
    </div>
    <div class="guide-note"><b>Catatan penting:</b> hasil kalkulator adalah estimasi berdasarkan angka yang kamu masukkan, bukan jaminan usaha pasti untung. Uji harga ke pelanggan, sisihkan dana darurat, dan perbarui biaya saat harga bahan berubah.</div>
    <div class="guide-actions"><button class="btn btn-primary" id="guideToHpp">Saya paham, hitung HPP →</button><button class="btn btn-light" id="guideToBep">Uji rencana balik modal</button></div>`;
  document.querySelector('main').appendChild(guide);
  $('#guideToHpp').onclick=()=>go('hpp');$('#guideToBep').onclick=()=>go('modal');
  const helps={materialCost:'Jumlah biaya semua bahan yang benar-benar terpakai untuk satu kali produksi.',packagingCost:'Contoh: cup, botol, kardus, label, plastik, atau sendok.',laborCost:'Upah orang yang mengerjakan produksi—termasuk nilai waktu kerja sendiri.',otherCost:'Contoh: gas, listrik produksi, ongkir bahan, bahan rusak, dan penyusutan alat.',productionQty:'Jumlah produk jadi yang layak dijual dari biaya di atas.',marginTarget:'Bagian harga jual yang ingin menjadi laba kotor. Untuk pemula, uji beberapa skenario.',initialCapital:'Uang awal untuk alat, renovasi, deposit sewa, stok awal, dan kebutuhan pembukaan.',monthlyRevenue:'Total penjualan sebulan sebelum dipotong biaya.',variableCost:'Biaya yang ikut naik saat penjualan bertambah, seperti bahan dan kemasan.',operationalCost:'Biaya menjalankan usaha per bulan, seperti sewa, gaji, listrik, internet, dan promosi.'};
  Object.entries(helps).forEach(([id,text])=>{const input=$('#'+id);if(input){const note=document.createElement('small');note.className='field-help';note.textContent=text;input.insertAdjacentElement('afterend',note)}});
}
installBeginnerGuide();
renderIngredients();renderProducts();renderCashier();renderDashboard();
